config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  devise_for :users
  resources :pages
  resources :tours
  resources :users
  namespace :admin do
    resources :tours
  end

end

app/models/tour.rb
class Tour < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tours

  def admin?
    is_admin
  end
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required

  def index
    @tours = Tour.all
  end

  def new
    @tour = Tour.new
  end

  def create
    @tour = Tour.new(tour_params)

    if @tour.save
      redirect_to tours_path(@tour)
    else
      render :back
    end
  end

  def edit
    @tour = Tour.find(params[:id])
  end

  def udpate
    @tour = Tour.find(params[:id])

    if @tour.update_attributes(tour_params)
      redirect_to tours_path(@tour)
    else
      render :back
    end
  end

  def destroy
    @tour = Tour.find(params[:id])
    @tour.destroy!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def admin_required
    if !current_user.admin?
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @tours = Tour.all
  end

  def show
    @tour = Tour.find(params[:id])
  end

  def new
    @tour = Tour.new
  end

  def create
    @tour = Tour.new(tour_params)
    @tour.user = current_user

    if @tour.save
      redirect_to tour_path(@tour)
      flash[:notice] = "新增旅程成功！"
    else
      render :back
      flash[:warning] = "有些錯誤，請更正！"
    end
  end

  def edit
    @tour = Tour.find(params[:id])

    if @tour.user != current_user
      redirect_to tour_path(@tour)
    end
  end

  def update
    @tour = Tour.find(params[:id])

    if @tour.update_attributes(tour_params)
      redirect_to tour_path(@tour)
      flash[:notice] = "修改旅程成功！"
    else
      render :back
      flash[:warning] = "有些錯誤，請更正！"
    end
  end

  private

  def tour_params
    params.require(:tour).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/admin/tours_helper.rb
module Admin::ToursHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/tours/edit.html.erb
<%= render "common/navbar" %>

<div class="container">
  <div class="row well">
    <div class="col-md-12">
      <h2>修改旅遊資訊</h2>
      <%= simple_form_for(@tour) do |f| %>
        <%= f.input :title %>
        <%= f.input :price %>
        <%= f.input :destination %>
        <%= f.input :description, as: :text %>
        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

<%= render "common/footer" %>

app/views/admin/tours/index.html.erb
<%= render "common/navbar" %>
<div class="container">
  <div class="row">
    <div class="col-md-3">

    </div>
    <div class="col-md-9">
      <ul>
        <% @tours.each do |tour|%>
        <li> <%= link_to(tour.title,tours_path(tour)) %> <%=link_to("編輯",edit_admin_tour_path(tour))%> \\<%=link_to("刪除",admin_tour_path(tour), method: :delete)%></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<%= render "common/footer" %>

app/views/common/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-3"><h4>Who We Are?</h4></div>
      <div class="col-md-3"><h4>Links</h4></div>
      <div class="col-md-3"><h4>Stay In Touch</h4></div>
      <div class="col-md-3"><h4>Get In Touch</h4></div>
    </div>
  </div>
</div>

app/views/common/_navbar.html.erb
<div class="nav navbar-default">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1><%= link_to("BuBuTour", pages_path) %></h1>
        <ul class="nav nav-pills navbar-right">
          <li> <%=link_to("How It Works","#") %> </li>
          <li> <%=link_to("Browse a Tour", tours_path) %></li>
          <li> <%=link_to("Find a Tour guy", users_path)%></li>
          <% if user_signed_in? %>
            <li> <%=link_to("Sign out", destroy_user_session_path, method: :delete) %></li>
          <% else %>
            <li> <%=link_to("Sign in", new_user_session_path) %></li>
          <% end %>
        </ul>
      </div>
      <hr>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>噗噗出遊</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
  <%=render "common/navbar" %>

  <div class="container text-center">
    <div class="row">
      <div class="col-md-6">
        <h2>為您省去安排交通與行程的煩惱！</h2>
        <h3>專業在地導遊為您規劃整體的行程，您只需要準備一顆輕鬆的心！</h3>

        <button type="button" class="btn btn-primary btn-lg">立刻探索旅程！</button>
        <p><%= link_to("或 為旅人規劃一個完美的旅程","#") %></p>
      </div>
      <div class="col-md-6"><p>出發與終點</p></div>
      <hr>
    </div>

    <div class="row text-center well">
      <div class="col-md-3"><i class="glyphicon glyphicon-th-list"></i><p class="lead">1.選定行程</p></div>
      <div class="col-md-3"><i class="glyphicon glyphicon-pencil"></i><p class="lead">2.挑選時間</p></div>
      <div class="col-md-3"><i class="glyphicon glyphicon-road"></i><p class="lead">3.出行！</p></div>
      <div class="col-md-3"><i class="glyphicon glyphicon-bed"></i><p class="lead">4.滿載而歸</p></div>
    </div>

    <div class="row well">
      <div class="col-md-6"><p>ＱＡ</p>
        <ul class="list-unstyled">
          <li>1.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus consequat ullamcorper suscipit. Nam sollicitudin tincidunt libero, eu ultricies risus congue et. Aliquam id convallis justo. Quisque sed sem ipsum. Cras sit amet libero non sapien congue euismod. Ut in sem velit. Aliquam sit amet lectus massa. In ultrices sed mauris quis accumsan. Pellentesque sit amet nunc et dolor dictum iaculis. Donec hendrerit, ante sit amet dictum gravida, lorem odio pretium arcu, eget consectetur neque dui sed sapien. Aliquam erat volutpat. Donec in nibh iaculis tellus luctus iaculis vel sit amet sem. Proin eleifend ex at viverra aliquam. Cras volutpat ipsum eget neque luctus ultrices. Nunc at efficitur est.</li>
          <li>2.Ut ut nisl porta, tristique mi id, convallis ex. Morbi sagittis, eros sit amet lobortis vehicula, eros sem pretium mi, ac cursus risus ipsum vulputate nisi. Mauris fringilla enim sit amet odio luctus pulvinar. Mauris nec tortor pretium, malesuada tellus id, mollis felis. Aenean sit amet eros at risus condimentum facilisis. Nullam commodo vel purus at dictum. Aenean placerat ante a placerat pretium. Mauris nec lacinia tellus. Vivamus fringilla magna a urna mollis hendrerit. Nullam ex nulla, ornare nec posuere id, gravida id mi. Suspendisse convallis, dolor in gravida ultricies, elit massa varius leo, ac cursus tortor lorem ut ipsum. Vestibulum gravida eget nulla sed finibus. Suspendisse sem elit, semper vitae lorem vitae, fringilla ultrices risus. Nunc sit amet velit sed justo molestie scelerisque at sit amet nisi. Maecenas suscipit quam nisl, et vulputate libero convallis non. Cras quis tortor sed dui dapibus accumsan mattis nec eros.</li>
          <li>3.Donec varius ipsum vel augue rutrum, eu venenatis magna scelerisque. Donec porta, diam vel accumsan elementum, augue neque interdum felis, a porta arcu nisi vel eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas semper felis nec tellus interdum consectetur vel eu odio. Nulla mollis consequat ligula, in gravida orci aliquet congue. Etiam lacus justo, accumsan ut pellentesque eget, tempus et mauris. Nulla mattis quam varius, eleifend nisl elementum, facilisis justo. Cras mattis luctus nibh vitae eleifend. Praesent quam nibh, porttitor eu dignissim vel, tristique sed urna. Vestibulum non enim eget leo aliquet euismod quis ut augue. Sed non diam sed eros blandit pulvinar. Mauris vitae semper massa. Cras eu sapien vitae quam tempor dictum eu vitae dolor.</li>
        </ul>
      </div>
      <div class="col-md-3"><p>導遊團隊</p></div>
    </div>
  </div>

  <div class="row well text-center">
    <div class="col-md-12"><p>見證報導</p></div>
  </div>
  </div>
<%= render "common/footer" %>

app/views/pages/show.html.erb
<%= render "common/navbar" %>
<div class="container">
  <div class="row well">
    <div class="col-md-12">
      <p>Search Bar</p>
    </div>
  </div>
  <div class="row border-between">
    <div class="col-md-9">
      <p>Tour List</p>
      <ul>
        <li>1.</li>
        <li>2.</li>
        <li>3.</li>
      </ul>
    </div>
    <div class="col-md-3">
      <p>Filter</p>
    </div>
  </div>
</div>
<%= render "common/footer" %>

app/views/pages/tour.html.erb
<%= render "common/navbar" %>

<div class="container">
  <div class="row">
    <div class="col-md-3"> User/Tour Profile</div>
    <div class="col-md-9"> Detail </div>
  </div>
</div>

<%= render "common/footer %>

app/views/tours/index.html.erb
<%= render "common/navbar" %>
<div class="container">
  <div class="row well">
    <div class="col-md-12">
      <p>Search Bar</p>
    </div>
  </div>
  <div class="row border-between">
    <div class="col-md-9">
      <p>Tour List</p>
      <ul>
        <% @tours.each do |tour| %>
          <li><%= link_to(tour.title, tour_path(tour)) %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-3">
      <p>Filter</p>
    </div>
  </div>
</div>
<%= render "common/footer" %>

app/views/tours/new.html.erb
<%= render "common/navbar" %>

<div class="container">
  <div class="row well">
    <div class="col-md-12">
      <h2>新增旅遊資訊</h2>
      <%= simple_form_for(@tour) do |f| %>
        <%= f.input :title %>
        <%= f.input :price %>
        <%= f.input :description, as: :text %>
        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

<%= render "common/footer" %>

app/views/tours/show.html.erb
<%= render "common/navbar" %>

<div class="container">
  <div class="alert alert-info" role="alert">
    <h3><%=link_to "#" do%> 參加這個旅行<% end %> or <%=link_to new_tour_path do%>創建一個這樣的旅行<% end %></h3>
  </div>
  <div class="row">
    <div class="col-md-3">
      <h2>細節</h2><hr>
      <h2>導遊資訊</h2><hr>
    </div>
    <div class="col-md-9">
      <% if user_signed_in? & current_user == @tour.user %>
        <%= link_to("修改旅遊", edit_tour_path(@tour), class: "btn btn-primary btn-sm") %>
      <% end %>
      <h2> <%= @tour.title %> </h2><hr>
      <p> <%= @tour.description %> </p><hr>
      <h2> QA </h2>
    </div>
  </div>
</div>

<%= render "common/footer" %>

app/views/users/index.html.erb
<%= render "common/navbar" %>
<div class="container">
  <div class="row well">
    <div class="col-md-12">
      <p>Search Bar</p>
    </div>
  </div>
  <div class="row border-between">
    <div class="col-md-9">
      <p>User List</p>
      <ul>
        <% @users.each do |user| %>
          <li><%= link_to(user.email, user_path(user)) %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-3">
      <p>Filter</p>
    </div>
  </div>
</div>
<%= render "common/footer" %>